# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Kat Anderson
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [9]:
# 1.1 Import Packages
from pathlib import Path
import pandas as pd

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [10]:
# 1.2 Set project folders using relative paths
project_fldr = Path.cwd().parent
raw_fldr = project_fldr / 'data' / 'raw'
processed_fldr = project_fldr / 'data' / 'processed'

print(project_fldr)
print(raw_fldr)
print(processed_fldr)

c:\ENV700
c:\ENV700\data\raw
c:\ENV700\data\processed

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [13]:
# 1.3 Create file path variables
epa_o3_24_path = raw_fldr / 'EPAair_O3_NC2024_raw.csv'
epa_o3_25_path = raw_fldr / 'EPAair_O3_NC2025_raw.csv'
epa_pm25_24_path = raw_fldr / 'EPAair_PM25_NC2024_raw.csv'
epa_pm25_25_path = raw_fldr / 'EPAair_PM25_NC2025_raw.csv'

paths = [epa_o3_24_path, epa_o3_25_path, epa_pm25_24_path, epa_pm25_25_path]

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [14]:
# 1.4 Read data into dataframes
epa_o3_24 = pd.read_csv(epa_o3_24_path)
epa_o3_25 = pd.read_csv(epa_o3_25_path)
epa_pm25_24 = pd.read_csv(epa_pm25_24_path)
epa_pm25_25 = pd.read_csv(epa_pm25_25_path)

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [15]:
# 1.5 Report the dimensions of each dataset
print('epa_o3_24 shape: ', epa_o3_24.shape)
print('epa_o3_25 shape: ', epa_o3_25.shape)
print('epa_pm25_24 shape: ', epa_pm25_24.shape)
print('epa_pm25_25 shape: ', epa_pm25_25.shape)

epa_o3_24 shape:  (9519, 21)
epa_o3_25 shape:  (9466, 21)
epa_pm25_24 shape:  (9752, 22)
epa_pm25_25 shape:  (10184, 22)

---
### 2. Wrangle individual datasets

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [20]:
# Convert the Date column to DateTime objects
epa_o3_24['Date'] = pd.to_datetime(epa_o3_24['Date'])
epa_o3_25['Date'] = pd.to_datetime(epa_o3_25['Date'])
epa_pm25_24['Date'] = pd.to_datetime(epa_pm25_24['Date'])
epa_pm25_25['Date'] = pd.to_datetime(epa_pm25_25['Date'])



# Print date ranges
print(min(epa_o3_24['Date']), max(epa_o3_24['Date']))
print(min(epa_o3_25['Date']), max(epa_o3_25['Date']))
print(min(epa_pm25_24['Date']), max(epa_pm25_24['Date']))
print(min(epa_pm25_25['Date']), max(epa_o3_24['Date']))

2024-01-01 00:00:00 2024-12-30 00:00:00
2025-01-01 00:00:00 2025-12-31 00:00:00
2024-01-01 00:00:00 2024-12-31 00:00:00
2025-01-01 00:00:00 2024-12-30 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [24]:
# 2.2 Subset columns
o3_24 = epa_o3_24[['Date', 'Daily AQI Value', 'Local Site Name',
                   'AQS Parameter Description', 'County', 'Site Latitude', 
                   'Site Longitude']]

o3_25 = epa_o3_25[['Date', 'Daily AQI Value', 'Local Site Name',
                   'AQS Parameter Description', 'County', 'Site Latitude', 
                   'Site Longitude']]

pm_24 = epa_pm25_24[['Date', 'Daily AQI Value', 'Local Site Name',
                   'AQS Parameter Description', 'County', 'Site Latitude', 
                   'Site Longitude']]

pm_25 = epa_pm25_25[['Date', 'Daily AQI Value', 'Local Site Name',
                   'AQS Parameter Description', 'County', 'Site Latitude', 
                   'Site Longitude']]

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [28]:
# 2.3 Update values
pm_24['AQS Parameter Description'] = 'PM 2.5'
pm_25['AQS Parameter Description'] = 'PM 2.5'

pm_25.head()

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
0,2025-01-01,4,Linville Falls,PM 2.5,Avery,35.972347,-81.933072
1,2025-01-04,7,Linville Falls,PM 2.5,Avery,35.972347,-81.933072
2,2025-01-07,8,Linville Falls,PM 2.5,Avery,35.972347,-81.933072
3,2025-01-10,23,Linville Falls,PM 2.5,Avery,35.972347,-81.933072
4,2025-01-13,28,Linville Falls,PM 2.5,Avery,35.972347,-81.933072

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [30]:
# 3.1 Ensure column are same across all dataframes

o3_24.info()
o3_25.info()
pm_24.info()
pm_25.info()

<class 'pandas.DataFrame'>
RangeIndex: 9519 entries, 0 to 9518
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       9519 non-null   datetime64[us]
 1   Daily AQI Value            9519 non-null   int64
 2   Local Site Name            9519 non-null   str
 3   AQS Parameter Description  9519 non-null   str
 4   County                     9519 non-null   str
 5   Site Latitude              9519 non-null   float64
 6   Site Longitude             9519 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 520.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 9466 entries, 0 to 9465
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       9466 non-null   datetime64[us]
 1   Daily AQI Value            9466 non-null   int64
 2   Local Site Name            9466 non-null   str
 3   AQS Parameter Description  9466 non-null   str
 4   County                     9466 non-null   str
 5   Site Latitude              9466 non-null   float64
 6   Site Longitude             9466 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 517.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       9752 non-null   datetime64[us]
 1   Daily AQI Value            9752 non-null   int64
 2   Local Site Name            9752 non-null   str
 3   AQS Parameter Description  9752 non-null   str
 4   County                     9752 non-null   str
 5   Site Latitude              9752 non-null   float64
 6   Site Longitude             9752 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 533.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 10184 entries, 0 to 10183
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       10184 non-null  datetime64[us]
 1   Daily AQI Value            10184 non-null  int64
 2   Local Site Name            10184 non-null  str
 3   AQS Parameter Description  10184 non-null  str
 4   County                     10184 non-null  str
 5   Site Latitude              10184 non-null  float64
 6   Site Longitude             10184 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 557.1 KB

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [33]:
# 3.2 Concatentate & report shape
dfs = [o3_24, o3_25, pm_24, pm_25]
complete_df = pd.concat(dfs, ignore_index = True)

complete_df.shape

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [34]:
# 3.3 View a sample of data
complete_df.sample(10, random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
26921,2024-07-20,24,Pitt Agri. Center,PM 2.5,Pitt,35.641276,-77.360126
6483,2024-04-22,40,University Meadows,Ozone,Mecklenburg,35.314158,-80.713469
34315,2025-02-18,53,Remount,PM 2.5,Mecklenburg,35.213171,-80.874084
12494,2025-08-08,39,Clemmons Middle,Ozone,Forsyth,36.026612,-80.341962
27781,2024-01-08,12,Old High School,PM 2.5,Swain,35.498711,-83.310242
23089,2024-08-26,59,Mendenhall School,PM 2.5,Guilford,36.109006,-79.802314
35024,2025-02-16,27,Spruce Pine Hospital,PM 2.5,Mitchell,35.912487,-82.062082
1157,2024-08-14,40,Beaufort,Ozone,Carteret,34.884800,-76.620300
4178,2024-09-14,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625
13592,2025-03-29,45,Waynesville School,Ozone,Haywood,35.507224,-82.963625

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [35]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
sites_oz24 = set(o3_24['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
sites_oz25 = set(o3_25['Local Site Name'])
sites_pm24 = set(pm_24['Local Site Name'])
sites_pm25 = set(pm_25['Local Site Name'])
## Compute the intersection 
common_sites = sites_oz24 & sites_oz25 & sites_pm24 & sites_pm25
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [39]:
# 4.1 Subset for records with sites in common
local_sites_df = complete_df[
    (complete_df["Local Site Name"].isin(common_sites))
]

local_sites_df.head()
local_sites_df.shape

(18778, 7)

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [42]:
# 4.2 Group and summarize data, then report its dimensions
summary_data = (
    local_sites_df
    .groupby(['Date', 'Local Site Name', 
              'AQS Parameter Description', 'County'])
    .agg(
        mean_daily_aqi=("Daily AQI Value", "mean"),
        mean_latitude=('Site Latitude', 'mean'),
        mean_longitude=('Site Longitude', 'mean')
    )
    .reset_index()
)

summary_data.shape

(17017, 7)

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [44]:
# 4.3 Calculate year and month columns

summary_data = summary_data.assign(
    year = lambda df: df['Date'].dt.year,
    month = lambda df: df['Date'].dt.month
)

summary_data.tail()

,Date,Local Site Name,AQS Parameter Description,County,mean_daily_aqi,mean_latitude,mean_longitude,year,month
17012,2025-12-31,Millbrook School,PM 2.5,Wake,24.0,35.856111,-78.574167,2025,12
17013,2025-12-31,Pitt Agri. Center,PM 2.5,Pitt,23.0,35.641276,-77.360126,2025,12
17014,2025-12-31,Rockwell,Ozone,Rowan,35.0,35.551868,-80.395039,2025,12
17015,2025-12-31,Rockwell,PM 2.5,Rowan,21.0,35.551868,-80.395039,2025,12
17016,2025-12-31,West Johnston Co.,PM 2.5,Johnston,25.0,35.590950,-78.462200,2025,12

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [56]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns
summary_data_reshaped = summary_data.pivot_table(
    index=['Date', 'month', 'year', 'Local Site Name','County','mean_latitude', 'mean_longitude'],
    columns='AQS Parameter Description', 
    values='mean_daily_aqi'
).reset_index()

summary_data_reshaped.head()

AQS Parameter Description,Date,month,year,Local Site Name,County,mean_latitude,mean_longitude,Ozone,PM 2.5
0,2024-01-01,1,2024,Bryson City,Swain,35.434767,-83.442133,NaN,43.0
1,2024-01-01,1,2024,Castle Hayne,New Hanover,34.364167,-77.838611,NaN,44.5
2,2024-01-01,1,2024,Clemmons Middle,Forsyth,36.026612,-80.341962,NaN,47.5
3,2024-01-01,1,2024,Durham Armory,Durham,36.032955,-78.904037,NaN,61.0
4,2024-01-01,1,2024,Frying Pan Mountain,Haywood,35.379167,-82.792500,NaN,14.0

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [57]:
# 5.1 Save the file
summary_data_reshaped.to_csv(processed_fldr/'EPAair_O3_PM25_NC2425_Processed.csv', index=False)

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [60]:
# 6.1 Generate a summary table and show its first 5 records
monthly_summary = (summary_data_reshaped
.groupby(['Local Site Name', 'month', 'year'])
.agg(
    mean_ozone=('Ozone', 'mean'),
    mean_pm25=('PM 2.5', 'mean')
)
.reset_index()
)

monthly_summary.head()

  Local Site Name  month  year  mean_ozone  mean_pm25
0     Bryson City      1  2024         NaN  22.580645
1     Bryson City      1  2025         NaN  25.838710
2     Bryson City      2  2024         NaN  32.000000
3     Bryson City      2  2025         NaN  32.678571
4     Bryson City      3  2024   40.709677  30.935484

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.